exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


title: Virtual Domain-Driven Design
description: The Virtual Domain-Driven Design is an online meetup to share DDDesign information
url: "https://virtualddd.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown