backend:
  name: github
  # change repo to your git repository url
  repo: Virtual-Domain-driven-design/virtual-domain-driven-design
  open_authoring: true

publish_mode: editorial_workflow

media_folder: src/images/uploads

site_url: https://virtualddd.com
display_url: https://virtualddd.com

collections:
  - name: "learning-ddd"
    label: "Learning DDD"
    files:
      - name: "books"
        label: "Books"
        file: "src/content/books.yaml"
        extension: "yaml"
        media_folder: ../images/books
        fields:
          - name: "books"
            label: "Books"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Image", name: "img", widget: "image", allow_multiple: false}
              - { label: "Level", name: "level", widget: "select", options: ["all", "beginner", "intermediate", "advanced"] }
              - { label: "Tags", name: "tags", widget: "list", hint: "List of comma seperated tags"}
      - name: "videos"
        label: "Videos"
        file: "src/content/videos.yaml"
        extension: "yaml"
        fields:
          - name: "videos"
            label: "Videos"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "video", widget: "string", hint: "Embedded link to the video, Example for youtube: https://youtube.com/embed/{id}" }
              - { label: "Level", name: "level", widget: "select", options: ["all", "beginner", "intermediate", "advanced"] }
              - { label: "Tags", name: "tags", widget: "list", hint: "List of comma seperated tags"}
      - name: "dddeu"
        label: "DDD Europe Videos"
        file: "src/content/dddeu.yaml"
        extension: "yaml"
        fields:
          - name: "videos"
            label: "Videos"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "video", widget: "string", hint: "Embedded link to the video, Example for youtube: https://youtube.com/embed/{id}" }
              - { label: "Level", name: "level", widget: "select", options: ["all", "beginner", "intermediate", "advanced"] }
              - { label: "Tags", name: "tags", widget: "list", hint: "List of comma seperated tags"}
      - name: "kandddinsky"
        label: "KanDDDinsky Videos"
        file: "src/content/kandddinsky.yaml"
        extension: "yaml"
        fields:
          - name: "videos"
            label: "Videos"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "video", widget: "string", hint: "Embedded link to the video, Example for youtube: https://youtube.com/embed/{id}" }
              - { label: "Level", name: "level", widget: "select", options: ["all", "beginner", "intermediate", "advanced"] }
              - { label: "Tags", name: "tags", widget: "list", hint: "List of comma seperated tags"}
      - name: "exploreddd"
        label: "ExploreDDD Videos"
        file: "src/content/exploreddd.yaml"
        extension: "yaml"
        fields:
          - name: "videos"
            label: "Videos"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "video", widget: "string", hint: "Embedded link to the video, Example for youtube: https://youtube.com/embed/{id}" }
              - { label: "Level", name: "level", widget: "select", options: ["all", "beginner", "intermediate", "advanced"] }
              - { label: "Tags", name: "tags", widget: "list", hint: "List of comma seperated tags"}
  - name: "communities"
    label: "DDD Communities"
    files:
      - name: "communities"
        label: "Communities"
        file: "src/content/communities.yaml"
        extension: "yaml"
        fields:
          - name: "communities"
            label: "Communities"
            widget: "list"
            summary: '{{fields.name}}'
            fields:
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Country", name: "country", widget: "string"}
              - { label: "City", name: "city", widget: "string", required: false}
              - { label: "Url", name: "url", widget: "string"}
              - { label: "Img", name: "img", widget: "string"}
