backend:
  name: github
  # change repo to your git repository url
  repo: Virtual-Domain-driven-design/virtual-domain-driven-design
  open_authoring: true

publish_mode: editorial_workflow

media_folder: src/images/uploads

site_url: https://virtualddd.com
display_url: https://virtualddd.com

collections:
  - name: "learning-ddd"
    label: "Learning DDD"
    files:
      - name: "books"
        label: "Books"
        file: "src/content/books.yml"
        extension: "yml"
        media_folder: ../images/books
        fields:
          - name: "books"
            label: "Books"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Image", name: "img", widget: "image", allow_multiple: false}
              - { label: "Tags", name: "tags", widget: "list"}
  - name: "communities"
    label: "DDD Communities"
    files:
      - name: "communities"
        label: "Communities"
        file: "src/content/communities.yml"
        extension: "yml"
        fields:
          - name: "communities"
            label: "Communities"
            widget: "list"
            summary: '{{fields.name}}'
            fields:
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Country", name: "country", widget: "string"}
              - { label: "City", name: "city", widget: "string", required: false}
              - { label: "Url", name: "url", widget: "string"}
              - { label: "Img", name: "img", widget: "string"}